// Copyright (c) Microsoft. All rights reserved.

#ifndef REAL_CHANNEL_INTERNAL_H
#define REAL_CHANNEL_INTERNAL_H

#include "macro_utils/macro_utils.h"
#include "../../inc/c_util/channel_internal.h"

#define R2(X) REGISTER_GLOBAL_MOCK_HOOK(X, real_##X);

#define REGISTER_CHANNEL_INTERNAL_GLOBAL_MOCK_HOOKS() \
    REGISTER_GLOBAL_MOCK_HOOK(THANDLE_MOVE(CHANNEL_INTERNAL), THANDLE_MOVE(real_CHANNEL_INTERNAL)) \
    REGISTER_GLOBAL_MOCK_HOOK(THANDLE_INITIALIZE(CHANNEL_INTERNAL), THANDLE_INITIALIZE(real_CHANNEL_INTERNAL)) \
    REGISTER_GLOBAL_MOCK_HOOK(THANDLE_INITIALIZE_MOVE(CHANNEL_INTERNAL), THANDLE_INITIALIZE_MOVE(real_CHANNEL_INTERNAL)) \
    REGISTER_GLOBAL_MOCK_HOOK(THANDLE_ASSIGN(CHANNEL_INTERNAL), THANDLE_ASSIGN(real_CHANNEL_INTERNAL)) \


#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

typedef struct CHANNEL_INTERNAL_TAG real_CHANNEL_INTERNAL;
THANDLE_TYPE_DECLARE(real_CHANNEL_INTERNAL);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif // REAL_CHANNEL_INTERNAL_H
