// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#ifndef REAL_CONSTBUFFER_THANDLE_RENAMES_H
#define REAL_CONSTBUFFER_THANDLE_RENAMES_H

#define CONSTBUFFER_THANDLE_Create real_CONSTBUFFER_THANDLE_Create
#define CONSTBUFFER_THANDLE_CreateFromBuffer real_CONSTBUFFER_THANDLE_CreateFromBuffer
#define CONSTBUFFER_THANDLE_CreateWithMoveMemory real_CONSTBUFFER_THANDLE_CreateWithMoveMemory
#define CONSTBUFFER_THANDLE_CreateWithCustomFree real_CONSTBUFFER_THANDLE_CreateWithCustomFree
#define CONSTBUFFER_THANDLE_CreateFromOffsetAndSize real_CONSTBUFFER_THANDLE_CreateFromOffsetAndSize
#define CONSTBUFFER_THANDLE_CreateFromOffsetAndSizeWithCopy real_CONSTBUFFER_THANDLE_CreateFromOffsetAndSizeWithCopy
#define CONSTBUFFER_THANDLE_GetContent real_CONSTBUFFER_THANDLE_GetContent
#define CONSTBUFFER_THANDLE_contain_same real_CONSTBUFFER_THANDLE_contain_same
#define CONSTBUFFER_THANDLE_get_serialization_size real_CONSTBUFFER_THANDLE_get_serialization_size
#define CONSTBUFFER_THANDLE_to_buffer real_CONSTBUFFER_THANDLE_to_buffer
#define CONSTBUFFER_THANDLE_to_fixed_size_buffer real_CONSTBUFFER_THANDLE_to_fixed_size_buffer
#define CONSTBUFFER_THANDLE_from_buffer real_CONSTBUFFER_THANDLE_from_buffer

#define CONSTBUFFER_THANDLE_TO_FIXED_SIZE_BUFFER_RESULT real_CONSTBUFFER_THANDLE_TO_FIXED_SIZE_BUFFER_RESULT
#define CONSTBUFFER_THANDLE_FROM_BUFFER_RESULT real_CONSTBUFFER_THANDLE_FROM_BUFFER_RESULT

#define CONSTBUFFER_THANDLE_CreateWritableHandle real_CONSTBUFFER_THANDLE_CreateWritableHandle
#define CONSTBUFFER_THANDLE_GetWritableBuffer real_CONSTBUFFER_THANDLE_GetWritableBuffer
#define CONSTBUFFER_THANDLE_SealWritableHandle real_CONSTBUFFER_THANDLE_SealWritableHandle
#define CONSTBUFFER_THANDLE_GetWritableBufferSize real_CONSTBUFFER_THANDLE_GetWritableBufferSize

#endif // REAL_CONSTBUFFER_THANDLE_RENAMES_H
