// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#include "c_util_reals_ut_pch.h"

BEGIN_TEST_SUITE(TEST_SUITE_NAME_FROM_CMAKE)

// this test makes sure that the mappings work
// (there is a real_ function corresponding to the original)
TEST_FUNCTION(check_all_c_util_reals) // no-srs
{
    // arrange

    // act
    REGISTER_ASYNC_OP_GLOBAL_MOCK_HOOKS();
    REGISTER_FILENAME_HELPER_GLOBAL_MOCK_HOOK();
    REGISTER_CHANNEL_GLOBAL_MOCK_HOOKS();
    REGISTER_CONSTBUFFER_GLOBAL_MOCK_HOOK();
    REGISTER_CONSTBUFFER_ARRAY_GLOBAL_MOCK_HOOK();
    REGISTER_CONSTBUFFER_ARRAY_SYNC_WRAPPER_GLOBAL_MOCK_HOOK();
    REGISTER_CONSTBUFFER_ARRAY_BATCHER_GLOBAL_MOCK_HOOK();
    REGISTER_CRITICAL_SECTION_GLOBAL_MOCK_HOOKS();
    REGISTER_DOUBLYLINKEDLIST_GLOBAL_MOCK_HOOKS();
    REGISTER_EXTERNAL_COMMAND_HELPER_GLOBAL_MOCK_HOOKS();
    REGISTER_MEMORY_DATA_GLOBAL_MOCK_HOOK();
    REGISTER_RC_PTR_GLOBAL_MOCK_HOOKS();
    REGISTER_RC_STRING_GLOBAL_MOCK_HOOKS();
    REGISTER_RC_STRING_UTILS_GLOBAL_MOCK_HOOKS();
    REGISTER_SINGLYLINKEDLIST_GLOBAL_MOCK_HOOKS();
    REGISTER_UUID_STRING_GLOBAL_MOCK_HOOK();
    REGISTER_HASH_GLOBAL_MOCK_HOOK();
    REGISTER_TCALL_DISPATCHER_CANCELLATION_TOKEN_CANCEL_CALL_GLOBAL_MOCK_HOOK();
    REGISTER_CANCELLATION_TOKEN_GLOBAL_MOCK_HOOKS();

#if defined _MSC_VER
    REGISTER_OBJECT_LIFETIME_TRACKER_GLOBAL_MOCK_HOOKS();
    REGISTER_WORKER_THREAD_GLOBAL_MOCK_HOOK();
    REGISTER_TCALL_DISPATCHER_THREAD_NOTIFICATION_CALL_GLOBAL_MOCK_HOOK();
    REGISTER_THREAD_NOTIFICATIONS_DISPATCHER_GLOBAL_MOCK_HOOK();
    REGISTER_THREAD_NOTIFICATIONS_LACKEY_DLL_GLOBAL_MOCK_HOOK();
#endif

    // assert
    // no explicit assert. if it builds, it works
}

END_TEST_SUITE(TEST_SUITE_NAME_FROM_CMAKE)
